name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./           # Local directory to upload
          server-dir: /www/raetast.com/  # Server directory to upload to
          # If the port is not the default FTP port (21), uncomment the line below and set the port:
          # port: ${{ secrets.FTP_PORT }}
